const mongoose = require('mongoose');

const { Schema } = mongoose;
const { DEPOSIT_REQUEST_STATUS, PAYMENT_METHOD } = require('../constants/depositStatuses');

/**
 * Immutable-style order record: one document is created per payment attempt.
 * Status transitions: PENDING → SUCCESS | FAILED.
 * Once SUCCESS or FAILED, the record is never mutated again (Idempotency).
 *
 * Financial integrity rules enforced here:
 *  - order_id is globally unique (sparse index prevents duplicate processing).
 *  - gateway_reference_id is unique-sparse so two webhook calls for the same
 *    gateway transaction ID cannot both credit the wallet.
 */
const depositRequestSchema = new Schema(
  {
    /**
     * Our internal order ID — generated by the service layer.
     * Format: "ORDER-<timestamp>-<random hex>"
     * Acts as the primary idempotency key passed to the payment gateway.
     */
    order_id: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      index: true
    },
    /** The spectator who initiated this top-up. */
    user_id: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true
    },
    /**
     * Snapshot of the package chosen at the time of order creation.
     * Stored as a string reference so historical orders remain readable
     * even if the original DepositPackage document is later deactivated.
     */
    package_id: {
      type: String,
      required: true,
      trim: true
    },
    /** VND amount charged to the user. Snapshot from package at order time. */
    total_vnd: {
      type: Number,
      required: true,
      min: [1000, 'Minimum deposit is 1,000 VND']
    },
    /**
     * Total tokens to credit = token_received + bonus_token.
     * Snapshot from package at order time to survive future package edits.
     */
    total_token: {
      type: Number,
      required: true,
      min: [1, 'total_token must be at least 1']
    },
    /**
     * Payment gateway / channel used for this order.
     * Validated against the PAYMENT_METHOD constant enum.
     */
    payment_method: {
      type: String,
      required: true,
      enum: Object.values(PAYMENT_METHOD),
      trim: true
    },
    /**
     * Order lifecycle state.
     * Transitions: PENDING → SUCCESS | FAILED
     * Final states (SUCCESS, FAILED) are write-protected by the service layer.
     */
    status: {
      type: String,
      required: true,
      enum: Object.values(DEPOSIT_REQUEST_STATUS),
      default: DEPOSIT_REQUEST_STATUS.PENDING,
      trim: true
    },
    /**
     * Transaction ID returned by the payment gateway after confirmation.
     * Used as the reference_id in the TransactionHistory audit log.
     * Unique-sparse: null is allowed (PENDING orders), but two SUCCESS records
     * cannot share the same gateway reference.
     */
    gateway_reference_id: {
      type: String,
      trim: true,
      index: { unique: true, sparse: true }
    },
    /** Optional human-readable note (e.g. failure reason from gateway). */
    note: {
      type: String,
      trim: true
    }
  },
  {
    collection: 'deposit_requests',
    timestamps: {
      createdAt: 'created_at',
      updatedAt: 'updated_at'
    },
    versionKey: false
  }
);

// Compound index: look up all orders for a user sorted by newest first
depositRequestSchema.index({ user_id: 1, created_at: -1 });
// Quickly filter by status for admin dashboards
depositRequestSchema.index({ status: 1, created_at: -1 });

module.exports = mongoose.model('DepositRequest', depositRequestSchema);
