module.exports = {
  User: require('./User'),
  Role: require('./Role'),
  UserRole: require('./UserRole'),
  HorseOwner: require('./HorseOwner'),
  Jockey: require('./Jockey'),
  RaceReferee: require('./RaceReferee'),
  Horse: require('./Horse'),
  HorseRatingHistory: require('./HorseRatingHistory'),
  Tournament: require('./Tournament'),
  Round: require('./Round'),
  Race: require('./Race'),
  Registration: require('./Registration'),
  RegistrationCancellationTicket: require('./RegistrationCancellationTicket'),
  JockeyAssignment: require('./JockeyAssignment'),
  HorseCheck: require('./HorseCheck'),
  RaceResult: require('./RaceResult'),
  Prize: require('./Prize'),
  PrizeAward: require('./PrizeAward'),
  Bet: require('./Bet'),
  RefereeReport: require('./RefereeReport'),
  Violation: require('./Violation'),
  Notification: require('./Notification'),
  RoleApplication: require('./RoleApplication'),
  RaceEngineRun: require('./RaceEngineRun'),
  RaceRun: require('./RaceRun'),
  RaceOddsMarket: require('./RaceOddsMarket'),
  // ── Wallet & Payment ──────────────────────────────────────────────────────
  Wallet: require('./Wallet'),
  TransactionHistory: require('./TransactionHistory'),
  RewardItem: require('./RewardItem'),
  RedemptionHistory: require('./RedemptionHistory'),
  // ── Deposit / Top-up ─────────────────────────────────────────────────────
  DepositPackage: require('./DepositPackage'),
  DepositRequest: require('./DepositRequest')
};
